const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const pages={dashboard:'经营总览',merchants:'商户管理',suppliers:'供应商管理',formats:'业态管理',standardIngredients:'标准食材',tenantProducts:'运营商品',tenantSkus:'SKU中心',productPublish:'发布记录',brandLibrary:'品牌库',productCategories:'分类库',productAuthorization:'商品授权',standardRecipes:'标准菜谱',dishes:'标准菜谱库',dishCategories:'分类管理',dishAuthorization:'菜谱授权',deviceRecipes:'设备菜谱',ingredients:'食材中心',purchase:'采购管理',permissions:'角色与权限'};
const merchantRows=[['杭州市校园餐饮管理中心','hzxycy','91330100MA2XY0012K','SH10001','K12 教育业态','浙江省杭州市','2027-08-01','正常',false],['西湖区学校后勤服务中心','xhxxhq','91330106MA2XY0023L','SH10002','K12 教育业态','浙江省杭州市','2027-03-16','正常',false],['南京未来教育服务中心','njwljy','91320100MA2XY0034M','SH10003','K12 教育业态','江苏省南京市','2026-09-30','正常',true],['上海青禾校园服务中心','shqhxy','91310100MA2XY0045N','SH10004','K12 教育业态','上海市','2027-05-20','正常',false],['深圳星海教育服务中心','szxhjy','91440300MA2XY0056P','SH10005','K12 教育业态','广东省深圳市','2026-08-15','已停用',false]];
const featureMap={suppliers:['供应商档案','合作关系','供货范围','结算配置','资质证照','绩效评估'],formats:['业态模板','营业模式','桌台规则','菜单策略','时段配置','门店参数'],dishes:['标准菜谱库','分类管理','规格与做法','区域定价','上下架管理','门店同步'],ingredients:['标准食材库','计量单位','食材分类','品牌规格','成本价格','菜谱关联'],purchase:['采购申请','采购订单','收货入库','退货处理','订单跟踪','对账结算'],permissions:['产品功能包','角色权限','数据权限','商户授权','成员角色','操作审计'],validity:['服务套餐','商户有效期','到期预警','续费记录','停启用管理','授权历史'],settings:['企业资料','组织架构','成员管理','消息通知','参数配置','接口管理']};
function showToast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function dashboard(){return `<div class="page-head"><div><h1>上午好，陈晓宇 👋</h1><p>这里是味来餐饮集团今日经营概况</p></div><span class="date-chip">2026年8月4日　星期二</span></div><div class="stats">${[['商户总数','128','较上月','+6.7%','▤'],['合作供应商','36','本月新增','+3 家','♧'],['本月采购额','¥ 826.4万','较上月','+12.6%','⇄'],['服务到期预警','6','30天内到期','需关注','◷']].map((x,i)=>`<div class="stat-card"><div class="stat-label"><span>${x[0]}</span><span class="stat-icon">${x[4]}</span></div><div class="stat-value">${x[1]}</div><div class="trend">${x[2]}　<b class="${i===3?'down':''}">${x[3]}</b></div></div>`).join('')}</div><div class="dashboard-grid"><div class="panel"><div class="panel-head"><h3>近7日经营趋势</h3><a>营业额　<span style="color:#bac5f7">订单量</span></a></div><div class="chart"><div class="chart-grid"></div><div class="bars">${[['62','39','07/29'],['72','48','07/30'],['58','42','07/31'],['81','55','08/01'],['75','61','08/02'],['88','68','08/03'],['92','72','08/04']].map(x=>`<div class="bar-group"><i class="bar" style="height:${x[0]}%"></i><i class="bar alt" style="height:${x[1]}%"></i><span>${x[2]}</span></div>`).join('')}</div></div></div><div class="panel"><div class="panel-head"><h3>商户营业额排行</h3><a>查看全部</a></div><div class="rank-list">${[['味来·滨江旗舰店','中式正餐','¥ 86,420'],['锅里见·星海店','火锅烧烤','¥ 72,680'],['青禾茶饮·中心广场店','茶饮烘焙','¥ 58,210'],['味来小馆·西湖店','中式正餐','¥ 45,890'],['米仓便当·未来城店','快餐简餐','¥ 39,760']].map((x,i)=>`<div class="rank"><span>${i+1}</span><div><b>${x[0]}</b><small>${x[1]}</small></div><strong>${x[2]}</strong></div>`).join('')}</div></div></div><div class="panel" style="margin-top:16px"><div class="panel-head"><h3>快捷入口</h3></div><div class="quick-grid">${[['＋','新建商户','快速开通商户'],['♧','新增供应商','建立合作关系'],['◉','创建菜谱','维护标准菜谱'],['⊞','配置权限','分配功能范围']].map(x=>`<button class="quick"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div></div>`}
function merchants(){return `<div class="page-head"><div><h1>商户管理</h1><p>管理租户下的商户档案、业态模板、功能范围及服务期限</p></div><div class="page-actions"><button class="ghost">导出商户</button><button class="primary" id="newMerchant">＋ 新建商户</button></div></div><div class="table-card"><div class="filters"><input class="search" id="merchantSearch" placeholder="⌕  搜索商户名称 / 账号 / 编码"/><select><option>全部业态模板</option><option>K12 教育业态</option></select><select id="merchantStatusFilter"><option value="">全部状态</option><option value="正常">正常</option><option value="已停用">已停用</option></select><select id="expiryFilter"><option value="">是否即将到期</option><option value="yes">即将到期</option><option value="no">非即将到期</option></select></div><table><thead><tr><th>商户信息</th><th>商户账号</th><th>业态模板</th><th>所在地区</th><th>服务有效期</th><th>状态</th><th>操作</th></tr></thead><tbody id="merchantBody">${merchantRows.map((row,i)=>merchantTr(row,i)).join('')}</tbody></table><div class="pagination">共 128 条　‹　<b>1</b>　2　3　…　13　›</div></div>`}
function merchantTr(r,i){let c=r[7]==='已停用'?'off':'';return `<tr data-status="${r[7]}" data-expiring="${r[8]?'yes':'no'}"><td><b>${r[0]}</b><span class="sub">编码：${r[3]}</span></td><td>${r[1]}</td><td>${r[4]}</td><td>${r[5]}</td><td>${r[6]}</td><td><span class="status ${c}">${r[7]}</span>${r[8]?'<span class="expiry-alert" title="该商户即将到期">◷ 即将到期</span>':''}</td><td><button class="link-btn merchant-action" data-mode="view" data-index="${i}">详情</button><button class="link-btn merchant-action" data-mode="edit" data-index="${i}">修改</button></td></tr>`}
function formats(){return `<div class="page-head"><div><h1>业态模板</h1><p>定义商户可创建的组织类型、上下级关系及层级规则</p></div><button class="primary" id="newFormat">＋ 新建业态模板</button></div>
<div class="format-layout">
  <section class="format-list panel"><div class="format-list-head"><b>模板列表</b><span>共 1 个</span></div><div class="format-search">⌕　搜索模板名称</div><button class="format-item active"><span class="format-logo">K12</span><span><b>K12 教育业态</b><small>教育局 → 学校 → 校区 → 食堂</small></span><i>›</i></button></section>
  <section class="format-detail panel">
    <div class="format-title"><div><span class="format-logo large">K12</span></div><div><h2>K12 教育业态</h2><p>适用于教育主管单位、学校及校园餐饮场景</p></div><div class="format-actions"><button class="primary" id="editFormat">编辑模板</button></div></div>
    <div class="format-meta"><div><span>模板编码</span><b>K12_EDU</b></div><div><span>已绑定商户</span><b>12 家</b></div><div><span>组织层级</span><b>4 级</b></div><div><span>最后更新</span><b>2026-08-04 10:28</b></div></div>
    <div class="section-title"><div><h3>组织层级模型</h3><p>商户绑定该模板后，将按照以下顺序创建和管理组织</p></div></div>
    <div class="org-flow">
      ${[['01','教育局','顶级组织','区域教育主管单位','◎'],['02','学校','二级组织','学校主体及独立核算单位','▣'],['03','校区','三级组织','学校下属教学或运营校区','◇'],['04','食堂','末级组织','校区内独立经营食堂','⌂']].map((x,i,a)=>`<div class="org-step"><div class="org-index">${x[0]}</div><div class="org-icon">${x[4]}</div><div class="org-copy"><div><b>${x[1]}</b><span>${x[2]}</span></div><p>${x[3]}</p></div><button class="level-config" data-name="${x[1]}" data-note="${x[3]}">配置</button>${i<a.length-1?'<i class="flow-line">↓</i>':''}</div>`).join('')}
    </div>
    <div class="rule-box" id="ruleBox"><b>层级约束</b><span>每个商户只能创建 1 个顶级教育局组织</span><span>学校、校区及食堂支持创建多个</span><span>下级组织必须归属于对应的直接上级组织</span><span>食堂为末级组织，不允许继续创建下级</span></div>
  </section>
</div>`}
function modulePage(key){const items=featureMap[key];return `<div class="empty-page"><div class="page-head"><div><h1>${pages[key]}</h1><p>统一管理${pages[key]}相关配置与业务数据</p></div><button class="primary">＋ 新建</button></div><div class="module-banner"><div><h2>${pages[key]}工作台</h2><p>标准化管理、统一配置，支撑多商户高效协同</p></div><span>${key==='suppliers'?'♧':'◈'}</span></div><div class="cards-grid">${items.map((x,i)=>`<div class="feature-card"><div class="fc-icon">${['▤','◈','⊞','⇄','◷','◎'][i]}</div><h3>${x}</h3><p>集中维护${x}，支持按商户和组织范围灵活配置。</p><button class="link-btn">进入管理 →</button></div>`).join('')}</div></div>`}
function roleManagement(){const roles=[['商户管理员','商户全业务管理角色','全部功能','全部字段可见','12'],['校区管理员','负责校区日常运营','组织、成员、菜谱、采购','证件号隐藏，手机脱敏','8'],['采购专员','负责采购申请与订单管理','采购、供应商查看','成本与银行账户隐藏','15'],['数据查看员','经营数据只读查看','工作台、经营报表','敏感字段全部脱敏','6']];return `<div class="page-head"><div><h1>角色与权限</h1><p>创建商户角色，通过功能权限和字段级数据权限控制商户人员的使用范围</p></div><div class="page-actions"><button class="ghost" id="assignRole">分配商户角色</button><button class="primary" id="newRole">＋ 创建角色</button></div></div><div class="role-summary"><div class="stat-card"><div class="stat-label">角色数量<span class="stat-icon">⊞</span></div><div class="stat-value">4</div><div class="trend">已配置商户端角色</div></div><div class="stat-card"><div class="stat-label">已分配商户<span class="stat-icon">▤</span></div><div class="stat-value">32</div><div class="trend">覆盖 <b>25%</b> 的商户</div></div><div class="stat-card"><div class="stat-label">待分配商户<span class="stat-icon">◷</span></div><div class="stat-value">96</div><div class="trend">请及时完成角色分配</div></div></div><div class="table-card"><div class="role-tabs"><button class="active">角色列表</button></div><div class="filters"><input class="search" placeholder="⌕  搜索角色名称"/><select><option>全部角色</option><option>含敏感字段权限</option><option>敏感字段脱敏</option></select></div><table><thead><tr><th>角色</th><th>功能权限</th><th>字段级数据权限</th><th>已分配商户</th><th>更新时间</th><th>操作</th></tr></thead><tbody>${roles.map((r,i)=>`<tr><td><div class="role-name"><span class="role-badge">${r[0][0]}</span><div><b>${r[0]}</b><span class="sub">${r[1]}</span></div></div></td><td><div class="permission-tags">${r[2].split('、').map(x=>`<span>${x}</span>`).join('')}</div></td><td>${r[3]}</td><td><span class="merchant-count">${r[4]} 家</span></td><td>2026-08-04</td><td><button class="link-btn role-edit">修改</button><button class="link-btn">删除</button></td></tr>`).join('')}</tbody></table></div>`}
function deviceRecipesPage(){return `<div class="empty-page"><div class="page-head"><div><h1>设备菜谱</h1><p>基于已上架菜谱配置人工处理与设备加工步骤</p></div></div><div class="module-banner"><div><h2>设备菜谱功能设计中</h2><p>后续将在此维护设备菜谱及其加工步骤配置。</p></div><span>▣</span></div></div>`}
const industryTypes={k12:{label:'K12 教育',note:'适用于教育主管单位、学校及校园餐饮场景',levels:[['教育局','区域教育主管单位'],['学校','学校主体及独立核算单位'],['校区','学校下属教学或运营校区'],['食堂','校区内独立经营食堂']]},enterprise:{label:'企事业食堂',note:'适用于机关、企事业单位内部餐饮场景',levels:[['企事业单位','用餐服务主体'],['园区','单位所属办公或生产园区'],['食堂','园区内独立经营食堂'],['档口','食堂内具体经营档口']]},chain:{label:'连锁餐饮',note:'适用于餐饮集团、品牌及连锁门店场景',levels:[['集团','餐饮集团总部'],['品牌','集团旗下经营品牌'],['区域','品牌所属经营区域'],['门店','具体经营门店']]}};
function openFormatEditor(mode){$('#formatModalTitle').textContent=mode==='edit'?'编辑业态模板':'新建业态模板';$('#formatModal').classList.remove('hidden');renderFormatEditor(mode,'k12')}
function renderFormatEditor(mode,type){const d=industryTypes[type];$('#formatEditorBody').innerHTML=`<div class="editor-basic three"><label>业态类型 <i>*</i><select id="industryType">${Object.entries(industryTypes).map(([k,v])=>`<option value="${k}" ${k===type?'selected':''}>${v.label}</option>`).join('')}</select><small>业态类型决定固定组织层级，保存后不可修改</small></label><label>业态名称 <i>*</i><input id="formatName" value="${mode==='edit'?'K12 教育业态':''}" placeholder="请输入业态名称" /></label><label>业态备注<textarea id="formatNote" rows="3" placeholder="请输入适用场景说明">${mode==='edit'?d.note:''}</textarea></label></div><div class="editor-level-head"><div><b>固定组织层级</b><span>层级类型和顺序由业态类型预设，不支持增加、删除或调整</span></div><span class="fixed-tag">系统预设</span></div><div class="fixed-levels">${d.levels.map((x,i)=>`<div class="fixed-level"><span>${String(i+1).padStart(2,'0')}</span><div><b>${x[0]}</b><small>${x[1]}</small></div>${i<d.levels.length-1?'<i>→</i>':''}</div>`).join('')}</div><div class="editor-tip">商户选择此模板后，将严格按照以上层级类型和顺序创建组织。</div><div class="editor-footer"><button class="ghost format-close">取消</button><button class="primary" id="saveFormat">保存模板</button></div>`;$('#industryType').onchange=e=>renderFormatEditor(mode,e.target.value);$$('.format-close').forEach(b=>b.onclick=()=>$('#formatModal').classList.add('hidden'));$('#saveFormat').onclick=()=>{if(!$('#formatName').value.trim())return showToast('请输入业态名称');$('#formatModal').classList.add('hidden');showToast(mode==='edit'?'模板修改成功':'业态模板创建成功')}}
const levelAttributes={
  '教育局':[['教育局名称','文本'],['统一社会信用代码','文本'],['行政区划','地区'],['办公地址','文本'],['负责人','文本'],['负责人联系电话','手机号']],
  '学校':[['学校名称','文本'],['学校统一代码','文本'],['学校类型','枚举'],['所属学段','多选'],['学校地址','文本'],['校长姓名','文本'],['联系电话','手机号'],['经营状态','枚举']],
  '校区':[['校区名称','文本'],['校区编码','文本'],['校区地址','文本'],['所属学校','关联'],['校区负责人','文本'],['联系电话','手机号'],['经营状态','枚举']],
  '食堂':[['食品经营许可证号','文本'],['统一社会信用代码','文本'],['食堂名称','文本'],['食堂地址','文本'],['经营模式','枚举'],['提供餐次','多选'],['食品安全总监','文本'],['食品安全管理员','文本'],['食堂负责人','文本'],['负责人联系电话','手机号'],['经营状态','枚举'],['食品经营性许可证图片','图片'],['营业执照','图片'],['前厅照片','图片'],['后厨照片','图片']]
};
function openLevelEditor(btn){const name=btn.dataset.name,attrs=levelAttributes[name]||[];$('#levelName').value=name;$('#levelNote').value=btn.dataset.note;$('#levelIcon').value='';$('#iconPreview').innerHTML='<span>＋</span><b>上传图标</b><small>PNG、JPG，建议 1:1</small>';$('#attributeCount').textContent=`${attrs.length} 项`;$('#attributeList').innerHTML=attrs.map((x,i)=>`<div class="attribute-item"><span>${String(i+1).padStart(2,'0')}</span><b>${x[0]}</b><em>${x[1]}</em></div>`).join('');$('#levelModal').classList.remove('hidden')}
function openMerchantOps(mode,index){const r=merchantRows[index],view=mode==='view';$('#merchantOpsTitle').textContent=view?'商户详情':'修改商户';$('#merchantOpsDesc').textContent=view?'查看商户基本信息及服务配置':'商户名称、账号、统一社会信用代码和商户编码不可修改';$('#merchantOpsBody').innerHTML=`<form id="merchantOpsForm" class="form-grid ops-form ${view?'readonly-form':''}"><label>商户名称<input value="${r[0]}" readonly><small class="locked-tip">商户名称不可修改</small></label><label>商户账号<input value="${r[1]}" readonly><small class="locked-tip">商户账号不可修改</small></label><label>统一社会信用代码<input value="${r[2]}" readonly><small class="locked-tip">统一社会信用代码不可修改</small></label><label>商户编码<input value="${r[3]}" readonly><small class="locked-tip">商户编码不可修改</small></label><label>业态模板<select disabled><option>${r[4]}</option></select><small class="locked-tip">业态模板创建后不可修改</small></label><label>联系人<input value="王老师" ${view?'readonly':''}></label><label>联系电话<input value="138****6618" ${view?'readonly':''}></label><label>服务有效期<input type="date" value="${r[6]}" ${view?'readonly':''}></label><label class="full">商户地址<input value="${r[5]} ${view?'教育服务中心':''}" ${view?'readonly':''}></label><label>当前状态<select ${view?'disabled':''}><option>${r[7]}</option><option>正常</option><option>停用</option></select></label><div class="form-actions full"><button type="button" class="ghost merchant-ops-close">${view?'关闭':'取消'}</button>${view?'':'<button class="primary">保存修改</button>'}</div></form>`;$('#merchantOpsModal').classList.remove('hidden');$$('.merchant-ops-close').forEach(b=>b.onclick=()=>$('#merchantOpsModal').classList.add('hidden'));if(!view)$('#merchantOpsForm').onsubmit=e=>{e.preventDefault();$('#merchantOpsModal').classList.add('hidden');showToast('商户信息修改成功')}}
function render(page='dashboard'){
  const title=pages[page];
  $('#breadcrumb').innerHTML=`首页 / <b>${title}</b>`;
  $('#content').innerHTML=page==='dashboard'?dashboard():page==='merchants'?merchants():page==='formats'?formats():page==='permissions'?roleManagement():page==='standardRecipes'?recipeStandardHub():page==='deviceRecipes'?'<div class="recipe-center-page"></div>':window.tenantProductPages?.includes(page)?tenantProductCenterPage(page):['dishes','dishCategories','dishAuthorization'].includes(page)?dishCenterPage(page):modulePage(page);
  $$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page||((page==='dishes'||page==='dishCategories')&&b.dataset.page==='standardRecipes')));
  if(page==='merchants')setTimeout(()=>{const applyMerchantFilters=()=>{const keyword=$('#merchantSearch').value.trim().toLowerCase(),status=$('#merchantStatusFilter').value,expiry=$('#expiryFilter').value;$$('#merchantBody tr').forEach(tr=>{const matchKeyword=!keyword||tr.innerText.toLowerCase().includes(keyword),matchStatus=!status||tr.dataset.status===status,matchExpiry=!expiry||tr.dataset.expiring===expiry;tr.style.display=matchKeyword&&matchStatus&&matchExpiry?'':'none'})};$('#newMerchant').onclick=()=>$('#modal').classList.remove('hidden');$('#merchantSearch').oninput=applyMerchantFilters;$('#merchantStatusFilter').onchange=applyMerchantFilters;$('#expiryFilter').onchange=applyMerchantFilters;$$('.merchant-action').forEach(b=>b.onclick=()=>openMerchantOps(b.dataset.mode,+b.dataset.index))},0);
  if(page==='formats')setTimeout(()=>{$('#editFormat').onclick=()=>openFormatEditor('edit');$('#newFormat').onclick=()=>openFormatEditor('new');$$('.level-config').forEach(b=>b.onclick=()=>openLevelEditor(b))},0);
  if(page==='permissions')setTimeout(()=>{$('#newRole').onclick=()=>$('#roleModal').classList.remove('hidden');$('#assignRole').onclick=()=>$('#assignRoleModal').classList.remove('hidden');$$('.role-edit').forEach(b=>b.onclick=()=>{$('#roleName').value=b.closest('tr').querySelector('.role-name b').textContent;$('#roleModal').classList.remove('hidden')})},0);
  if(page==='standardRecipes')setTimeout(bindRecipeStandardHub,0);
  if(page==='deviceRecipes')setTimeout(()=>window.renderDeviceRecipeHub?.(),0);
  if(window.tenantProductPages?.includes(page))setTimeout(()=>bindTenantProductCenter(page),0);
  if(['dishes','dishCategories','dishAuthorization'].includes(page))setTimeout(()=>bindDishCenter(page),0);
}
$('#loginForm').onsubmit=e=>{e.preventDefault();if(!$('#username').value||!$('#password').value)return showToast('请输入账号和密码');$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');render()};
$('#togglePwd').onclick=()=>{const p=$('#password');p.type=p.type==='password'?'text':'password';$('#togglePwd').textContent=p.type==='password'?'查看':'隐藏'};
$('#nav').onclick=e=>{const b=e.target.closest('button[data-page]');if(b)render(b.dataset.page)};
$('#logoutBtn').onclick=()=>{$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden')};
$('#closeModal').onclick=$('#cancelModal').onclick=()=>$('#modal').classList.add('hidden');
$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};
$('#merchantForm').onsubmit=e=>{e.preventDefault();$('#modal').classList.add('hidden');showToast('商户创建成功')};
$('#queryCredit').onclick=()=>{const code=$('#creditQuery').value.trim().toUpperCase();if(!/^[0-9A-Z]{18}$/.test(code))return showToast('请输入正确的18位统一社会信用代码');$('#createMerchantName').value='杭州市校园餐饮管理中心';$('#createContact').value='王老师';$('#createAddress').value='浙江省杭州市西湖区文教路88号';showToast('已查询到企业信息并自动带入')};
$$('.merchant-ops-close').forEach(b=>b.onclick=()=>$('#merchantOpsModal').classList.add('hidden'));
$$('.level-close').forEach(b=>b.onclick=()=>$('#levelModal').classList.add('hidden'));
$('#levelIcon').onchange=e=>{const file=e.target.files[0];if(!file)return;if(!file.type.startsWith('image/'))return showToast('请选择图片文件');const reader=new FileReader();reader.onload=ev=>$('#iconPreview').innerHTML=`<img src="${ev.target.result}" alt="组织图标预览"><b>更换图标</b>`;reader.readAsDataURL(file)};
$('#levelForm').onsubmit=e=>{e.preventDefault();$('#levelModal').classList.add('hidden');showToast('层级配置已保存')};
$$('.role-close').forEach(b=>b.onclick=()=>$('#roleModal').classList.add('hidden'));
$('#roleForm').onsubmit=e=>{e.preventDefault();$('#roleModal').classList.add('hidden');showToast('商户角色创建成功')};
$$('.assign-close').forEach(b=>b.onclick=()=>$('#assignRoleModal').classList.add('hidden'));
$('#assignRoleForm').onsubmit=e=>{e.preventDefault();$('#assignRoleModal').classList.add('hidden');showToast('商户角色分配成功')};
