const authorizedDeviceModels=[
  {id:'robot-a8',name:'智能炒菜机器人 A8',type:'炒菜机器人',brand:'厨智科技',model:'CR-A8',crafts:['炒制','炖制','收汁'],status:'有效',valid:'2027-08-01',params:[{key:'temperature',name:'锅温',unit:'℃',min:80,max:220,default:180},{key:'duration',name:'加工时间',unit:'分钟',min:1,max:60,default:8},{key:'speed',name:'搅拌档位',unit:'档',min:1,max:5,default:3}]},
  {id:'oven-s12',name:'万能蒸烤箱 S12',type:'蒸烤箱',brand:'膳能设备',model:'SKX-S12',crafts:['蒸制','烘烤'],status:'有效',valid:'2027-06-30',params:[{key:'temperature',name:'腔体温度',unit:'℃',min:30,max:250,default:180},{key:'duration',name:'加工时间',unit:'分钟',min:1,max:180,default:20},{key:'humidity',name:'湿度',unit:'%',min:0,max:100,default:60}]},
  {id:'steamer-z6',name:'智能蒸箱 Z6',type:'蒸箱',brand:'云厨电器',model:'ZX-Z6',crafts:['蒸制'],status:'有效',valid:'2027-03-31',params:[{key:'temperature',name:'蒸汽温度',unit:'℃',min:80,max:120,default:100},{key:'duration',name:'加工时间',unit:'分钟',min:1,max:120,default:15}]},
  {id:'robot-b5',name:'炒菜机器人 B5',type:'炒菜机器人',brand:'厨智科技',model:'CR-B5',crafts:['炒制','炖制'],status:'已失效',valid:'2026-08-20',params:[{key:'temperature',name:'锅温',unit:'℃',min:80,max:210,default:170},{key:'duration',name:'加工时间',unit:'分钟',min:1,max:45,default:8}]}
];

const deviceRecipeRecords=[
  {id:'DR202608001',name:'宫保鸡丁-A8标准方案',source:'宫保鸡丁',version:'V2.0',devices:['智能炒菜机器人 A8'],deviceSteps:2,totalSteps:5,status:'可用',updated:'2026-08-28 16:20'},
  {id:'DR202608002',name:'红烧肉-A8慢炖方案',source:'红烧肉',version:'V1.3',devices:['智能炒菜机器人 A8'],deviceSteps:2,totalSteps:6,status:'草稿',updated:'2026-08-27 11:05'},
  {id:'DR202608003',name:'清炒时蔬-S12方案',source:'清炒时蔬',version:'V1.0',devices:['万能蒸烤箱 S12'],deviceSteps:1,totalSteps:4,status:'可用',updated:'2026-08-26 09:42'},
  {id:'DR202608004',name:'红烧肉-B5历史方案',source:'红烧肉',version:'V1.1',devices:['炒菜机器人 B5'],deviceSteps:2,totalSteps:6,status:'异常',updated:'2026-08-22 14:18'}
];

const deviceRecipeSourceSteps={
  1:[['原料预处理','将五花肉洗净切成约3厘米见方的块。'],['焯水','冷水下锅焯水，撇去浮沫后捞出。'],['炒制上色','加入冰糖和五花肉翻炒上色。'],['炖制','加入调味料和清水炖至软烂。'],['收汁','大火收汁至汤汁浓稠。'],['装盘','检查成熟度后装盘。']],
  2:[['切配','鸡胸肉切丁，准备花生米和配料。'],['腌制','加入调味料腌制10分钟。'],['滑炒','鸡丁入锅快速滑炒至变色。'],['调味收汁','加入碗汁和配料翻炒收汁。'],['装盘','检查口味和成熟度后装盘。']],
  4:[['原料准备','蔬菜洗净并完成切配。'],['炒制','高温快速翻炒。'],['调味','加入调味料翻炒均匀。'],['装盘','保持蔬菜色泽并装盘。']]
};

let deviceRecipeDraft=null;

function deviceRecipesPage(){return `<div class="device-recipe-page"><div class="page-head"><div><h1>设备菜谱</h1><p>基于已上架菜谱配置人工处理与设备加工步骤</p></div><div class="page-actions"><button class="ghost" id="viewAuthorizedDevices">查看可用设备</button><button class="primary" id="createDeviceRecipe">＋ 新建设备菜谱</button></div></div><div class="device-summary"><div class="device-summary-card"><span>全部设备菜谱</span><b>${deviceRecipeRecords.length}</b></div><div class="device-summary-card"><span>可用</span><b>${deviceRecipeRecords.filter(x=>x.status==='可用').length}</b></div><div class="device-summary-card"><span>草稿</span><b>${deviceRecipeRecords.filter(x=>x.status==='草稿').length}</b></div><div class="device-summary-card"><span>授权异常</span><b>${deviceRecipeRecords.filter(x=>x.status==='异常').length}</b></div></div><div class="table-card"><div class="filters"><input class="search" id="deviceRecipeKeyword" placeholder="⌕ 搜索设备菜谱名称 / 编号"><select id="deviceRecipeModelFilter"><option value="">全部设备型号</option>${authorizedDeviceModels.filter(x=>x.status==='有效').map(x=>`<option>${x.name}</option>`).join('')}</select><select id="deviceRecipeStatusFilter"><option value="">全部状态</option><option>草稿</option><option>可用</option><option>已停用</option><option>异常</option></select></div><table><thead><tr><th>设备菜谱信息</th><th>来源菜谱</th><th>使用设备</th><th>设备加工步骤</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody id="deviceRecipeBody">${deviceRecipeRows()}</tbody></table></div></div>`}

function deviceRecipeRows(){return deviceRecipeRecords.map((r,i)=>`<tr data-keyword="${r.name} ${r.id}" data-devices="${r.devices.join(',')}" data-status="${r.status}"><td><b>${r.name}</b><span class="sub">${r.id}</span></td><td><b>${r.source}</b><span class="sub">来源版本 ${r.version}</span></td><td><div class="device-tags">${r.devices.map(x=>`<span class="device-tag">${x}</span>`).join('')}</div>${r.status==='异常'?'<span class="device-warning">设备授权已失效</span>':''}</td><td>${r.deviceSteps} / ${r.totalSteps} 个步骤</td><td><span class="device-recipe-status ${r.status==='草稿'?'draft':r.status==='异常'?'error':r.status==='已停用'?'off':''}">${r.status}</span></td><td>${r.updated}</td><td><button class="link-btn device-recipe-view" data-index="${i}">查看</button><button class="link-btn device-recipe-edit" data-index="${i}">编辑</button><button class="link-btn device-recipe-copy" data-index="${i}">复制</button>${r.status==='可用'?`<button class="link-btn device-recipe-disable" data-index="${i}">停用</button>`:''}</td></tr>`).join('')}

function bindDeviceRecipes(){
  const filter=()=>{const k=$('#deviceRecipeKeyword').value.toLowerCase(),d=$('#deviceRecipeModelFilter').value,s=$('#deviceRecipeStatusFilter').value;$$('#deviceRecipeBody tr').forEach(r=>r.hidden=!((!k||r.dataset.keyword.toLowerCase().includes(k))&&(!d||r.dataset.devices.includes(d))&&(!s||r.dataset.status===s)))};
  $('#deviceRecipeKeyword').oninput=filter;$('#deviceRecipeModelFilter').onchange=filter;$('#deviceRecipeStatusFilter').onchange=filter;
  $('#createDeviceRecipe').onclick=()=>openDeviceRecipeWizard();$('#viewAuthorizedDevices').onclick=openAuthorizedDeviceList;
  $$('.device-recipe-view').forEach(b=>b.onclick=()=>openDeviceRecipeDetail(+b.dataset.index));
  $$('.device-recipe-edit').forEach(b=>b.onclick=()=>openDeviceRecipeWizard(deviceRecipeRecords[+b.dataset.index],+b.dataset.index));
  $$('.device-recipe-copy').forEach(b=>b.onclick=()=>{const x=deviceRecipeRecords[+b.dataset.index];openDeviceRecipeWizard({...x,name:x.name+'-副本'})});
  $$('.device-recipe-disable').forEach(b=>b.onclick=()=>{deviceRecipeRecords[+b.dataset.index].status='已停用';showToast('设备菜谱已停用');render('deviceRecipes')});
}

function deviceModal(title,desc,body){document.querySelector('#deviceRecipeModalMask')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="device-recipe-modal-mask" id="deviceRecipeModalMask"><div class="device-recipe-modal"><div class="device-modal-head"><div><h2>${title}</h2><p>${desc}</p></div><button id="closeDeviceRecipeModal">×</button></div>${body}</div></div>`);$('#closeDeviceRecipeModal').onclick=()=>$('#deviceRecipeModalMask').remove()}

function openAuthorizedDeviceList(){deviceModal('可用设备','查看运营端授权给当前租户的设备型号与能力',`<div class="device-modal-body"><div class="readonly-banner">设备型号、工艺能力和参数模板由运营端统一维护，租户端仅可查看。</div><div class="available-device-list">${authorizedDeviceModels.map(d=>`<div class="available-device-card"><div class="available-device-card-head"><div><h3>${d.name}</h3><p>${d.brand} · ${d.model} · ${d.type}</p></div><span class="device-recipe-status ${d.status==='有效'?'':'error'}">${d.status}</span></div><div class="device-capabilities">${d.crafts.map(x=>`<span>${x}</span>`).join('')}</div><div class="device-param-summary"><b>参数模板</b><br>${d.params.map(p=>`${p.name}：${p.min}–${p.max} ${p.unit}`).join('　')}<br>授权有效期：${d.valid}</div></div>`).join('')}</div></div><div class="device-modal-foot"><div class="spacer"></div><button class="primary" id="deviceListClose">关闭</button></div>`);$('#deviceListClose').onclick=()=>$('#deviceRecipeModalMask').remove()}

function openDeviceRecipeWizard(existing=null,recordIndex=null){
  const sources=tenantDishes.filter(x=>x.status==='已上架'&&x.category);
  const selected=existing?sources.find(x=>x.name===existing.source)||sources[0]:null;
  deviceRecipeDraft={step:1,source:selected,name:existing?.name||'',activeStep:0,steps:[],recordIndex};
  if(selected)initializeDeviceSteps(selected);
  deviceModal(existing?'编辑设备菜谱':'新建设备菜谱','从已上架菜谱生成独立的人工与设备加工方案','<div id="deviceWizardSteps"></div><div class="device-modal-body" id="deviceWizardBody"></div><div class="device-modal-foot"><button class="ghost" id="cancelDeviceWizard">取消</button><button class="ghost" id="saveDeviceDraft">保存草稿</button><div class="spacer"></div><button class="ghost" id="prevDeviceWizard" hidden>上一步</button><button class="primary" id="nextDeviceWizard">下一步</button></div>');
  $('#cancelDeviceWizard').onclick=()=>$('#deviceRecipeModalMask').remove();$('#prevDeviceWizard').onclick=()=>{deviceRecipeDraft.step--;drawDeviceWizard()};$('#nextDeviceWizard').onclick=advanceDeviceWizard;$('#saveDeviceDraft').onclick=()=>persistDeviceRecipe('草稿');drawDeviceWizard();
}

function initializeDeviceSteps(source){const raw=deviceRecipeSourceSteps[source.id]||[['原料准备','完成原料清洗和切配。'],['加工处理','按照菜谱要求完成加工。'],['装盘','检查成品并装盘。']];deviceRecipeDraft.steps=raw.map((x,i)=>({name:x[0],instruction:x[1],mode:'manual',deviceId:'',craft:'',params:{},standard:i===raw.length-1?'符合出品标准':'',attention:''}))}

function drawWizardSteps(){const labels=['选择来源菜谱','配置加工步骤','确认生成'];$('#deviceWizardSteps').className='device-modal-steps';$('#deviceWizardSteps').innerHTML=labels.map((x,i)=>`<span class="device-modal-step ${deviceRecipeDraft.step===i+1?'active':deviceRecipeDraft.step>i+1?'done':''}"><i>${deviceRecipeDraft.step>i+1?'✓':i+1}</i>${x}</span>`).join('')}

function drawDeviceWizard(){drawWizardSteps();$('#prevDeviceWizard').hidden=deviceRecipeDraft.step===1;$('#nextDeviceWizard').textContent=deviceRecipeDraft.step===3?'生成设备菜谱':'下一步';if(deviceRecipeDraft.step===1)drawDeviceSourceStep();else if(deviceRecipeDraft.step===2)drawDeviceConfigStep();else drawDeviceConfirmStep()}

function drawDeviceSourceStep(){const sources=tenantDishes.filter(x=>x.status==='已上架'&&x.category);$('#deviceWizardBody').innerHTML=`<div class="recipe-choice-tools"><input id="deviceSourceSearch" placeholder="搜索菜谱名称或编号"><span class="readonly-banner" style="margin:0">仅展示已上架且已完善分类的菜谱</span></div><div class="recipe-choice-list" id="deviceSourceList">${sources.map(s=>`<label class="recipe-choice ${deviceRecipeDraft.source?.id===s.id?'active':''}" data-source-id="${s.id}" data-keyword="${s.name} ${s.code}"><input type="radio" name="deviceSource" ${deviceRecipeDraft.source?.id===s.id?'checked':''}><span><b>${s.name}</b><small>${s.code} · ${s.category}</small><small>${s.ingredients} 项用料 · ${(deviceRecipeSourceSteps[s.id]||[]).length||3} 个工艺步骤 · ${s.source}</small></span></label>`).join('')}</div>`;$$('.recipe-choice').forEach(c=>c.onclick=()=>{deviceRecipeDraft.source=sources.find(x=>x.id==c.dataset.sourceId);initializeDeviceSteps(deviceRecipeDraft.source);$$('.recipe-choice').forEach(x=>x.classList.toggle('active',x===c))});$('#deviceSourceSearch').oninput=e=>$$('.recipe-choice').forEach(c=>c.hidden=!c.dataset.keyword.toLowerCase().includes(e.target.value.toLowerCase()))}

function drawDeviceConfigStep(){const i=deviceRecipeDraft.activeStep,s=deviceRecipeDraft.steps[i];$('#deviceWizardBody').innerHTML=`<div class="device-config-layout"><aside class="process-step-nav"><h3>完整加工流程（${deviceRecipeDraft.steps.length} 步）</h3>${deviceRecipeDraft.steps.map((x,n)=>`<button class="process-step-button ${n===i?'active':''}" data-step-index="${n}"><i>${n+1}</i><span>${x.name}</span><em class="step-mode-badge ${x.mode==='device'?'device':''}">${x.mode==='device'?'设备加工':'人工处理'}</em></button>`).join('')}</aside><section class="process-config-card"><div class="process-config-title"><div><h3>步骤 ${i+1} · ${s.name}</h3><p>人工步骤可修改说明；设备步骤需完成设备和参数配置</p></div><div class="mode-switch"><button class="${s.mode==='manual'?'active':''}" data-step-mode="manual">人工处理</button><button class="${s.mode==='device'?'active':''}" data-step-mode="device">设备加工</button></div></div><div class="process-form-grid"><label class="full">步骤名称<input id="deviceStepName" value="${s.name}"></label><label class="full">操作要求<textarea id="deviceStepInstruction">${s.instruction}</textarea></label>${s.mode==='manual'?`<div class="manual-tip">该步骤由人工完成，不需要关联设备。修改内容仅保存到当前设备菜谱，不影响来源菜谱。</div>`:deviceStepFields(s)}<label class="full">完成标准<input id="deviceStepStandard" value="${s.standard}" placeholder="请输入该步骤的完成标准"></label><label class="full">注意事项<input id="deviceStepAttention" value="${s.attention}" placeholder="请输入安全或操作注意事项"></label></div></section></div>`;bindDeviceConfigControls()}

function deviceStepFields(s){const devices=authorizedDeviceModels.filter(x=>x.status==='有效'),d=devices.find(x=>x.id===s.deviceId);return `<label>设备型号 <i>*</i><select id="deviceStepModel"><option value="">请选择已授权设备</option>${devices.map(x=>`<option value="${x.id}" ${x.id===s.deviceId?'selected':''}>${x.name} · ${x.model}</option>`).join('')}</select></label><label>设备工艺 <i>*</i><select id="deviceStepCraft"><option value="">请选择加工工艺</option>${(d?.crafts||[]).map(x=>`<option ${x===s.craft?'selected':''}>${x}</option>`).join('')}</select></label><div class="parameter-box"><h4>设备参数</h4>${d?`<div class="parameter-grid">${d.params.map(p=>`<label class="parameter-field">${p.name} <i>*</i><input class="device-param-input" data-param="${p.key}" type="number" min="${p.min}" max="${p.max}" value="${s.params[p.key]??p.default}"><small>${p.min}–${p.max} ${p.unit}</small></label>`).join('')}</div>`:'<div class="manual-tip">选择设备后，系统将加载运营端定义的参数模板、单位和取值范围。</div>'}</div><label class="full">人工衔接说明<textarea id="deviceStepHandoff" placeholder="如：将腌制后的鸡丁倒入设备，完成后取出装盘">${s.handoff||''}</textarea></label>`}

function syncCurrentDeviceStep(){const s=deviceRecipeDraft.steps[deviceRecipeDraft.activeStep];if($('#deviceStepName'))s.name=$('#deviceStepName').value;if($('#deviceStepInstruction'))s.instruction=$('#deviceStepInstruction').value;if($('#deviceStepStandard'))s.standard=$('#deviceStepStandard').value;if($('#deviceStepAttention'))s.attention=$('#deviceStepAttention').value;if($('#deviceStepHandoff'))s.handoff=$('#deviceStepHandoff').value;if($('#deviceStepModel'))s.deviceId=$('#deviceStepModel').value;if($('#deviceStepCraft'))s.craft=$('#deviceStepCraft').value;$$('.device-param-input').forEach(x=>s.params[x.dataset.param]=x.value)}

function bindDeviceConfigControls(){$$('.process-step-button').forEach(b=>b.onclick=()=>{syncCurrentDeviceStep();deviceRecipeDraft.activeStep=+b.dataset.stepIndex;drawDeviceConfigStep()});$$('[data-step-mode]').forEach(b=>b.onclick=()=>{syncCurrentDeviceStep();const s=deviceRecipeDraft.steps[deviceRecipeDraft.activeStep];s.mode=b.dataset.stepMode;if(s.mode==='manual'){s.deviceId='';s.craft='';s.params={}}drawDeviceConfigStep()});if($('#deviceStepModel'))$('#deviceStepModel').onchange=e=>{syncCurrentDeviceStep();const s=deviceRecipeDraft.steps[deviceRecipeDraft.activeStep];s.deviceId=e.target.value;s.craft='';s.params={};drawDeviceConfigStep()}}

function validateDeviceSteps(){syncCurrentDeviceStep();const deviceSteps=deviceRecipeDraft.steps.filter(x=>x.mode==='device');if(!deviceSteps.length)return '请至少将一个工艺步骤设置为设备加工';for(const s of deviceSteps){if(!s.deviceId)return `请为“${s.name}”选择设备型号`;if(!s.craft)return `请为“${s.name}”选择设备工艺`;const d=authorizedDeviceModels.find(x=>x.id===s.deviceId);for(const p of d.params){const v=Number(s.params[p.key]??p.default);if(!Number.isFinite(v)||v<p.min||v>p.max)return `“${s.name}”的${p.name}应在 ${p.min}–${p.max} ${p.unit}之间`}}return ''}

function drawDeviceConfirmStep(){const ds=deviceRecipeDraft.steps.filter(x=>x.mode==='device'),used=[...new Set(ds.map(x=>x.deviceId))].map(id=>authorizedDeviceModels.find(x=>x.id===id));if(!deviceRecipeDraft.name)deviceRecipeDraft.name=`${deviceRecipeDraft.source.name}-${used.map(x=>x.model).join('+')}方案`;$('#deviceWizardBody').innerHTML=`<div class="device-confirm-head"><div class="device-confirm-metric"><span>全部步骤</span><b>${deviceRecipeDraft.steps.length}</b></div><div class="device-confirm-metric"><span>人工步骤</span><b>${deviceRecipeDraft.steps.length-ds.length}</b></div><div class="device-confirm-metric"><span>设备步骤</span><b>${ds.length}</b></div><div class="device-confirm-metric"><span>使用设备</span><b>${used.length}</b></div></div><section class="device-confirm-section"><h3>基本信息</h3><div class="device-basic-grid"><label>设备菜谱名称<input id="deviceRecipeName" value="${deviceRecipeDraft.name}"></label><label>来源菜谱<input value="${deviceRecipeDraft.source.name} · 当前版本" disabled></label></div></section><section class="device-confirm-section"><h3>加工流程确认</h3>${deviceRecipeDraft.steps.map((s,i)=>{const d=authorizedDeviceModels.find(x=>x.id===s.deviceId);return `<div class="confirm-step-row"><b>${i+1}</b><span>${s.name}</span><span class="step-mode-badge ${s.mode==='device'?'device':''}">${s.mode==='device'?'设备加工':'人工处理'}</span><span>${d?`${d.name} · ${s.craft}`:'无需设备'}</span></div>`}).join('')}</section><div class="readonly-banner">生成后形成独立设备菜谱，不会反向修改来源菜谱。本期不下发真实设备，也不包含商户授权。</div>`;$('#deviceRecipeName').oninput=e=>deviceRecipeDraft.name=e.target.value}

function persistDeviceRecipe(status){if(!deviceRecipeDraft.source)return showToast('请选择一个已上架菜谱');syncCurrentDeviceStep();const ds=deviceRecipeDraft.steps.filter(x=>x.mode==='device'),devices=[...new Set(ds.map(x=>x.deviceId))].map(id=>authorizedDeviceModels.find(x=>x.id===id)?.name).filter(Boolean),record={id:deviceRecipeDraft.recordIndex===null?`DR${new Date().getFullYear()}${String(deviceRecipeRecords.length+5).padStart(5,'0')}`:deviceRecipeRecords[deviceRecipeDraft.recordIndex].id,name:deviceRecipeDraft.name||`${deviceRecipeDraft.source.name}-设备方案`,source:deviceRecipeDraft.source.name,version:'当前版本',devices,deviceSteps:ds.length,totalSteps:deviceRecipeDraft.steps.length,status,updated:'刚刚'};if(deviceRecipeDraft.recordIndex===null)deviceRecipeRecords.unshift(record);else deviceRecipeRecords[deviceRecipeDraft.recordIndex]=record;$('#deviceRecipeModalMask').remove();showToast(status==='草稿'?'设备菜谱草稿已保存':'设备菜谱已生成');render('deviceRecipes')}

function advanceDeviceWizard(){if(deviceRecipeDraft.step===1){if(!deviceRecipeDraft.source)return showToast('请选择一个已上架菜谱');deviceRecipeDraft.step=2;drawDeviceWizard();return}if(deviceRecipeDraft.step===2){const error=validateDeviceSteps();if(error)return showToast(error);deviceRecipeDraft.step=3;drawDeviceWizard();return}if(!deviceRecipeDraft.name.trim())return showToast('请输入设备菜谱名称');persistDeviceRecipe('可用')}

function openDeviceRecipeDetail(index){const r=deviceRecipeRecords[index];deviceModal('设备菜谱详情',`${r.id} · 来源于 ${r.source}`,`<div class="device-modal-body"><div class="device-confirm-head"><div class="device-confirm-metric"><span>当前状态</span><b style="font-size:16px">${r.status}</b></div><div class="device-confirm-metric"><span>来源版本</span><b>${r.version}</b></div><div class="device-confirm-metric"><span>设备步骤</span><b>${r.deviceSteps}</b></div><div class="device-confirm-metric"><span>全部步骤</span><b>${r.totalSteps}</b></div></div><section class="device-confirm-section"><h3>${r.name}</h3><p class="muted">使用设备：${r.devices.join('、')}</p></section>${Array.from({length:r.totalSteps},(_,i)=>`<div class="detail-step"><div class="detail-step-head"><b>步骤 ${i+1} · ${i<r.totalSteps-r.deviceSteps?'人工处理':'设备加工'}</b><span class="step-mode-badge ${i>=r.totalSteps-r.deviceSteps?'device':''}">${i<r.totalSteps-r.deviceSteps?'无需设备':r.devices[0]}</span></div><p>${i<r.totalSteps-r.deviceSteps?'按照设备菜谱中的人工操作要求完成处理。':'按照运营端参数模板完成设备加工配置。'}</p></div>`).join('')}</div><div class="device-modal-foot"><div class="spacer"></div><button class="primary" id="deviceDetailClose">关闭</button></div>`);$('#deviceDetailClose').onclick=()=>$('#deviceRecipeModalMask').remove()}
