const tenantCategories=[{id:'c1',name:'热菜',children:['大荤','小荤','半荤半素','素菜']},{id:'c2',name:'主食',children:['米饭','面食','点心']},{id:'c3',name:'汤粥',children:['汤类','粥类']}];
// 分类状态与排序：停用/删除只改状态、不从结构里移除，保证历史归属可追溯（不自动下架或删除已上架菜谱）。
const categoryMeta={};
tenantCategories.forEach((p,pi)=>{categoryMeta[`${p.name}/`]={status:'启用',sort:pi+1};p.children.forEach((c,ci)=>{categoryMeta[`${p.name}/${c}`]={status:'启用',sort:ci+1}})});
categoryMeta['主食/点心']={status:'已停用',sort:3};
categoryMeta['热菜/半荤半素']={status:'已删除',sort:3};
const categoryMetaKey=(level,parent,name)=>level==='一级分类'?`${name}/`:`${parent}/${name}`;
const categoryUsable=key=>categoryMeta[key]?.status==='启用';
const dishCountOf=cat=>(typeof tenantDishes==='undefined'?[]:tenantDishes).filter(d=>(d.category||'')===cat||(d.category||'').startsWith(cat+' / ')).length;
function categoryRows(){return tenantCategories.flatMap(p=>[{level:'一级分类',name:p.name,parent:'-',sort:categoryMeta[`${p.name}/`].sort,status:categoryMeta[`${p.name}/`].status,count:dishCountOf(p.name)},...p.children.map(c=>({level:'二级分类',name:c,parent:p.name,sort:categoryMeta[`${p.name}/${c}`].sort,status:categoryMeta[`${p.name}/${c}`].status,count:dishCountOf(`${p.name} / ${c}`)}))])}
const tenantDishes=[
 {id:1,code:'ZC202608001',name:'红烧肉',category:'热菜 / 大荤',source:'自行创建',ingredients:6,status:'已上架',authorized:12,updated:'2026-08-25',newVersion:false},
 {id:2,code:'ZC202608002',name:'宫保鸡丁',category:'热菜 / 小荤',source:'标准菜谱引用',ingredients:8,status:'已上架',authorized:8,updated:'2026-08-24',newVersion:true},
 {id:3,code:'ZC202608003',name:'紫菜蛋花汤',category:'汤粥 / 汤类',source:'标准菜谱引用',ingredients:5,status:'已下架',authorized:0,updated:'2026-08-23',newVersion:false},
 {id:4,code:'ZC202608004',name:'青椒土豆丝',category:'热菜 / 素菜',source:'自行创建',ingredients:4,status:'已下架',authorized:0,updated:'2026-08-22',newVersion:false}
];
const standardDishes=[
 {id:'s1',code:'BZ20260018',name:'宫保鸡丁',category:'热菜 / 小荤',source:'平台标准菜谱库',ingredients:8,status:'已引用',version:'V2.1',updated:'2026-08-26'},
 {id:'s2',code:'BZ20260035',name:'紫菜蛋花汤',category:'汤粥 / 汤类',source:'平台标准菜谱库',ingredients:5,status:'已引用',version:'V1.3',updated:'2026-08-18'},
 {id:'s3',code:'BZ20260042',name:'清炒时蔬',category:'热菜 / 素菜',source:'教育营养菜谱库',ingredients:4,status:'未引用',version:'V1.0',updated:'2026-08-15'},
 {id:'s4',code:'BZ20260057',name:'土豆烧牛肉',category:'热菜 / 大荤',source:'平台标准菜谱库',ingredients:7,status:'未引用',version:'V1.2',updated:'2026-08-12'}
];
const authorizations=[
 {dish:'红烧肉',code:'ZC202608001',category:'热菜 / 大荤',merchants:['杭州市校园餐饮管理中心','西湖区学校后勤服务中心','南京未来教育服务中心'],count:12,updated:'2026-08-26'},
 {dish:'宫保鸡丁',code:'ZC202608002',category:'热菜 / 小荤',merchants:['杭州市校园餐饮管理中心','上海青禾校园服务中心'],count:8,updated:'2026-08-25'}
];
const dishPageHead=(title,desc,actions='')=>`<div class="page-head"><div><h1>${title}</h1><p>${desc}</p></div><div class="page-actions">${actions}</div></div>`;
const dishInfo=d=>`<div class="dish-info"><span class="dish-img">菜谱</span><div><b>${d.name}${d.newVersion?'<span class="version-tag">有新授权版本</span>':''}</b><small>${d.code}</small></div></div>`;
function dishCenterPage(page){if(page==='dishes')return myDishPage();if(page==='standardDishes')return standardDishPage();if(page==='dishCategories')return categoryPage();return authorizationPage()}
function myDishPage(){return `<div class="dish-page">${dishPageHead('我的菜谱库','维护租户自行创建或从标准菜谱库引用的私域菜谱','<button class="primary" id="createDish">＋ 新建菜谱</button>')}<div class="dish-kpis"><div class="dish-kpi"><span>全部菜谱</span><b>86</b></div><div class="dish-kpi"><span>已上架</span><b>62</b></div><div class="dish-kpi"><span>有上游新版本</span><b>3</b></div></div><div class="table-card"><div class="filters"><input id="dishKeyword" class="search" placeholder="⌕ 搜索菜谱名称 / 编号"><select id="dishSource"><option value="">全部来源</option><option>自行创建</option><option>标准菜谱引用</option></select><select id="dishState"><option value="">全部状态</option><option>已上架</option><option>已下架</option></select><select><option>全部分类</option><option>热菜 / 大荤</option><option>热菜 / 小荤</option><option>汤粥 / 汤类</option></select></div><table><thead><tr><th>菜谱信息</th><th>分类</th><th>来源</th><th>用料数</th><th>状态</th><th>已授权商户</th><th>操作</th></tr></thead><tbody id="myDishBody">${tenantDishes.map(d=>myDishRow(d)).join('')}</tbody></table></div></div>`}
function myDishRow(d){return `<tr data-name="${d.name} ${d.code}" data-source="${d.source}" data-state="${d.status}"><td>${dishInfo(d)}</td><td>${d.category}</td><td><span class="source-tag ${d.source==='自行创建'?'self':''}">${d.source}</span></td><td>${d.ingredients}</td><td><span class="dish-status ${d.status==='已下架'?'off':''}">${d.status}</span></td><td><button class="link-btn dish-auth-detail" data-id="${d.id}">${d.authorized} 家</button></td><td class="dish-actions"><button class="link-btn dish-view" data-id="${d.id}">查看</button><button class="link-btn dish-edit" data-id="${d.id}">编辑</button><button class="link-btn dish-toggle" data-id="${d.id}">${d.status==='已上架'?'下架':'上架'}</button><button class="link-btn dish-delete" data-id="${d.id}">删除</button></td></tr>`}
function standardDishPage(){return `<div class="dish-page">${dishPageHead('标准菜谱库','查看运营端授权使用的标准菜谱，引用后进入我的菜谱库','<button class="primary" id="batchReferenceDish">批量引用</button>')}<div class="readonly-banner">标准菜谱由运营端授权，仅支持查看和引用，不可编辑、删除或上下架。</div><div class="table-card"><div class="filters"><input id="standardKeyword" class="search" placeholder="⌕ 搜索菜谱名称 / 编号"><select id="standardRefState"><option value="">全部引用状态</option><option>未引用</option><option>已引用</option></select><select><option>全部标准分类</option><option>热菜 / 大荤</option><option>热菜 / 小荤</option><option>汤粥 / 汤类</option></select></div><table><thead><tr><th><input type="checkbox"></th><th>菜谱信息</th><th>标准分类</th><th>授权来源</th><th>用料数</th><th>版本</th><th>引用状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody id="standardDishBody">${standardDishes.map(d=>`<tr data-name="${d.name} ${d.code}" data-state="${d.status}"><td><input class="standard-check" type="checkbox" value="${d.id}"></td><td>${dishInfo(d)}</td><td>${d.category}</td><td>${d.source}</td><td>${d.ingredients}</td><td>${d.version}</td><td><span class="dish-status ${d.status==='未引用'?'off':''}">${d.status}</span></td><td>${d.updated}</td><td><button class="link-btn standard-view" data-id="${d.id}">查看</button><button class="link-btn standard-reference" data-id="${d.id}">引用</button></td></tr>`).join('')}</tbody></table></div></div>`}
function categoryPage(){const rows=categoryRows();return `<div class="dish-page">${dishPageHead('分类管理','自建一级、二级分类，用于统一管理租户菜谱','<button class="primary" id="newPrimaryCategory">＋ 新增一级分类</button>')}<div class="category-layout-v2"><aside class="category-tree-v2"><h3>分类结构</h3><div class="category-node-v2 active" data-category="all">全部分类 <span>${rows.length}</span></div>${tenantCategories.map(p=>`<div class="category-node-v2" data-category="${p.name}">▾ ${p.name}<span>${p.children.length}</span></div>${p.children.map(c=>`<div class="category-node-v2 child" data-category="${c}">${c}</div>`).join('')}`).join('')}</aside><section class="category-main-v2"><div class="category-main-head-v2"><h3 id="categoryTitleV2">全部分类</h3><button class="primary" id="newSecondaryCategory">＋ 新增二级分类</button></div><table><thead><tr><th>分类名称</th><th>层级</th><th>上级分类</th><th>菜谱数量</th><th>排序</th><th>状态</th><th>操作</th></tr></thead><tbody id="categoryBodyV2">${rows.map(r=>`<tr data-category-row="${r.name}" data-parent="${r.parent}" data-level="${r.level}"><td><b>${r.name}</b></td><td>${r.level}</td><td>${r.parent}</td><td>${r.count}</td><td>${r.sort}</td><td><span class="dish-status ${r.status==='启用'?'':'off'}">${r.status}</span></td><td>${r.status==='已删除'?'<span class="sub">已删除，仅保留历史归属</span>':`<button class="link-btn category-edit">编辑</button><button class="link-btn category-toggle">${r.status==='启用'?'停用':'启用'}</button><button class="link-btn category-delete">删除</button>`}</td></tr>`).join('')}</tbody></table></section></div></div>`}
function authorizationPage(){return `<div class="dish-page">${dishPageHead('菜谱授权','将我的菜谱库中已上架的菜谱授权给一个或多个商户','<button class="primary" id="newDishAuthorization">＋ 新增授权</button>')}<div class="table-card"><div class="dish-tabs"><button class="active" data-auth-view="dish">按菜谱查看</button><button data-auth-view="merchant">按商户查看</button></div><div class="filters"><input class="search" id="authKeyword" placeholder="⌕ 搜索菜谱 / 商户"><div class="auth-view-switch"><button class="active">全部授权</button><button>近期新增</button></div></div><div id="authorizationTable">${authorizationByDish()}</div></div></div>`}
function authorizationByDish(){return `<table><thead><tr><th>菜谱信息</th><th>分类</th><th>授权商户</th><th>授权商户数</th><th>更新时间</th><th>操作</th></tr></thead><tbody>${authorizations.map((a,i)=>`<tr><td><b>${a.dish}</b><span class="sub">${a.code}</span></td><td>${a.category}</td><td><div class="merchant-pills">${a.merchants.slice(0,2).map(x=>`<span>${x}</span>`).join('')}${a.count>2?`<span>+${a.count-2}</span>`:''}</div></td><td>${a.count} 家</td><td>${a.updated}</td><td><button class="link-btn auth-edit" data-index="${i}">新增/删除商户</button><button class="link-btn auth-remove" data-index="${i}">解除授权</button></td></tr>`).join('')}</tbody></table>`}
function authorizationByMerchant(){return `<table><thead><tr><th>商户</th><th>业态模板</th><th>已授权菜谱</th><th>菜谱数</th><th>更新时间</th><th>操作</th></tr></thead><tbody><tr><td><b>杭州市校园餐饮管理中心</b><span class="sub">hzxycy</span></td><td>K12 教育业态</td><td><div class="merchant-pills"><span>红烧肉</span><span>宫保鸡丁</span></div></td><td>16 个</td><td>2026-08-26</td><td><button class="link-btn auth-edit">新增/删除菜谱</button></td></tr><tr><td><b>西湖区学校后勤服务中心</b><span class="sub">xhxxhq</span></td><td>K12 教育业态</td><td><div class="merchant-pills"><span>红烧肉</span></div></td><td>8 个</td><td>2026-08-25</td><td><button class="link-btn auth-edit">新增/删除菜谱</button></td></tr></tbody></table>`}
function dishDrawer(title,body,save='保存'){document.querySelector('#dishDrawerMask')?.remove();document.body.insertAdjacentHTML('beforeend',`<div id="dishDrawerMask" class="modal"><div class="modal-card dish-drawer"><div class="modal-head"><div><h3>${title}</h3><p>菜谱中心 · 租户私域数据</p></div><button class="dish-drawer-close">×</button></div>${body}<div class="editor-footer"><button class="ghost dish-drawer-close">取消</button>${save?`<button id="dishDrawerSave" class="primary">${save}</button>`:''}</div></div></div>`);$$('.dish-drawer-close').forEach(b=>b.onclick=()=>$('#dishDrawerMask').remove())}
function dishEditor(d=null,readonly=false){dishDrawer(readonly?'查看菜谱':d?'编辑菜谱':'新建菜谱',`<div class="dish-form-section"><h4>一、基本信息</h4><div class="dish-form-grid"><label>菜谱编号<input value="${d?.code||'系统自动生成'}" disabled></label><label>菜谱名称<input value="${d?.name||''}" ${readonly?'disabled':''}></label></div></div><div class="dish-form-section"><h4>二、用料明细</h4></div><div class="dish-form-section"><h4>三、烹饪工艺与制作步骤</h4></div><div class="dish-form-section"><h4>四、营养预览</h4></div>`,readonly?'':'保存草稿')}
function standardDetail(d){dishDrawer('标准菜谱详情',`<div class="readonly-banner">标准菜谱为只读内容，引用后可进入我的菜谱库维护。</div><div class="dish-form-section"><h4>一、基本信息</h4><div class="dish-form-grid"><label>标准菜谱编号<input value="${d.code}" disabled></label><label>菜谱名称<input value="${d.name}" disabled></label></div></div><div class="dish-form-section"><h4>二、用料明细</h4></div><div class="dish-form-section"><h4>三、烹饪工艺与制作步骤</h4></div><div class="dish-form-section"><h4>四、营养预览</h4></div>`,'')}
function referenceDrawer(items){const groups=[...new Map(items.map(d=>[d.category,{category:d.category,items:items.filter(x=>x.category===d.category)}])).values()],options='<option value="">请选择自建二级分类</option><option>热菜 / 大荤</option><option>热菜 / 小荤</option><option>热菜 / 素菜</option><option>汤粥 / 汤类</option>';dishDrawer(`引用标准菜谱（${items.length}个）`,`<div class="flow-steps"><span class="active">1 选择菜谱</span><span class="active">2 指定分类</span><span>3 引用完成</span></div><div class="readonly-banner">引用后在“我的菜谱库”生成独立私域副本，默认为下架状态。</div>${items.length>1?'<div class="reference-mode-tabs"><button class="active" data-reference-mode="item">按菜谱指定分类</button><button data-reference-mode="category">按源分类批量映射</button></div>':''}<div id="itemMapping" class="mapping-box">${items.map(d=>`<div class="mapping-row"><div><b>${d.name}</b><small>${d.category} · ${d.code}</small></div><span>存入</span><select class="reference-category">${options}</select></div>`).join('')}</div>${items.length>1?`<div id="categoryMapping" class="mapping-box" hidden>${groups.map(g=>`<div class="mapping-row"><div><b>${g.category}</b><small>该源分类下已选择 ${g.items.length} 个菜谱</small></div><span>批量存入</span><select class="reference-group-category">${options}</select></div>`).join('')}</div>`:''}`,'确认引用');$$('[data-reference-mode]').forEach(b=>b.onclick=()=>{$$('[data-reference-mode]').forEach(x=>x.classList.toggle('active',x===b));const byCategory=b.dataset.referenceMode==='category';$('#itemMapping').hidden=byCategory;$('#categoryMapping').hidden=!byCategory});$('#dishDrawerSave').onclick=()=>{const activeSelects=$('#categoryMapping')&&!$('#categoryMapping').hidden?$$('.reference-group-category'):$$('.reference-category');if([...activeSelects].some(s=>!s.value))return showToast('请完成全部分类映射');$('#dishDrawerMask').remove();showToast(`成功引用 ${items.length} 个菜谱，已生成下架草稿`)}}
function categoryEditor(level,existing=null,parentName=''){const isEdit=!!existing;const parents=tenantCategories.filter(p=>categoryMeta[`${p.name}/`].status!=='已删除');const chosen=existing?existing.parent:parentName;dishDrawer(isEdit?'编辑分类':`新增${level}`,`<div class="dish-form-section"><div class="dish-form-grid"><label>分类层级<input value="${level}" disabled></label>${level==='二级分类'?`<label>上级分类<select id="categoryParent">${parents.map(p=>`<option ${chosen===p.name?'selected':''}>${p.name}</option>`).join('')}</select></label>`:''}<label>分类名称<input id="newCategoryName" value="${existing?existing.name:''}" placeholder="请输入分类名称"></label><label>排序值<input id="categorySort" type="number" min="1" value="${existing?existing.sort:1}"></label></div></div>`,isEdit?'保存':'确认创建');$('#dishDrawerSave').onclick=()=>{const name=$('#newCategoryName').value.trim(),sort=Number($('#categorySort').value)||1,parent=level==='二级分类'?($('#categoryParent')?.value||''):'';if(!name)return showToast('请输入分类名称');const siblings=level==='二级分类'?(tenantCategories.find(p=>p.name===parent)?.children||[]):tenantCategories.map(p=>p.name);if(siblings.some(x=>x===name&&x!==(existing?existing.name:'')))return showToast('同级分类下已存在同名分类');const oldKey=isEdit?categoryMetaKey(level,existing.parent,existing.name):'';const prev=isEdit?Object.assign({},categoryMeta[oldKey]):{status:'启用'};if(isEdit){if(level==='二级分类'){const op=tenantCategories.find(x=>x.name===existing.parent);if(op){const idx=op.children.indexOf(existing.name);if(idx>-1)op.children.splice(idx,1)}const np=tenantCategories.find(x=>x.name===parent);if(np&&!np.children.includes(name))np.children.push(name);const from=`${existing.parent} / ${existing.name}`,to=`${parent} / ${name}`;tenantDishes.forEach(d=>{if((d.category||'')===from)d.category=to})}else{const p=tenantCategories.find(x=>x.name===existing.name);Object.keys(categoryMeta).forEach(k=>{if(k.startsWith(existing.name+'/')){categoryMeta[name+'/'+k.slice(existing.name.length+1)]=categoryMeta[k];delete categoryMeta[k]}});tenantDishes.forEach(d=>{const c=d.category||'';if(c===existing.name||c.startsWith(existing.name+' / '))d.category=name+c.slice(existing.name.length)});if(p)p.name=name}delete categoryMeta[oldKey];categoryMeta[categoryMetaKey(level,parent,name)]=Object.assign(prev,{sort})}else{if(level==='二级分类'){const p=tenantCategories.find(x=>x.name===parent);if(!p)return showToast('请选择上级分类');p.children.push(name)}else{tenantCategories.push({id:'c'+(tenantCategories.length+1),name,children:[]})}categoryMeta[categoryMetaKey(level,parent,name)]={status:'启用',sort}}$('#dishDrawerMask').remove();showToast(isEdit?'分类已保存':`${level}创建成功`);render('dishCategories')}}
function authorizationDrawer(){dishDrawer('新增菜谱授权',`<div class="flow-steps"><span class="active">1 选择菜谱</span><span class="active">2 选择商户</span><span>3 确认授权</span></div><div class="dish-form-section"><h4>选择菜谱</h4><p>仅展示已上架的菜谱</p><div class="select-list">${tenantDishes.filter(d=>d.status==='已上架').map(d=>`<div class="select-row"><input type="checkbox" class="auth-dish-check"><label><b>${d.name}</b><small>${d.code} · ${d.category}</small></label></div>`).join('')}</div></div><div class="dish-form-section"><h4>选择商户</h4><p>支持同时授权给一个或多个商户，不设置授权有效期</p><div class="select-list">${merchantRows.slice(0,4).map(m=>`<div class="select-row"><input type="checkbox" class="auth-merchant-check"><label><b>${m[0]}</b><small>${m[1]} · ${m[4]}</small></label></div>`).join('')}</div></div><div class="readonly-banner">商户只能查看被授权的源菜谱，必须先引用到商户私域菜谱库后才能编辑和使用。</div>`,'确认授权');$('#dishDrawerSave').onclick=()=>{if(!$$('.auth-dish-check:checked').length)return showToast('请至少选择一个菜谱');if(!$$('.auth-merchant-check:checked').length)return showToast('请至少选择一个商户');$('#dishDrawerMask').remove();showToast('菜谱授权成功')}}
function bindDishCenter(page){if(page==='dishes'){const filter=()=>{const k=$('#dishKeyword').value.toLowerCase(),s=$('#dishSource').value,st=$('#dishState').value;$$('#myDishBody tr').forEach(r=>r.style.display=(!k||r.dataset.name.toLowerCase().includes(k))&&(!s||r.dataset.source===s)&&(!st||r.dataset.state===st)?'':'none')};$('#dishKeyword').oninput=filter;$('#dishSource').onchange=filter;$('#dishState').onchange=filter;$('#createDish').onclick=()=>dishEditor();$$('.dish-view').forEach(b=>b.onclick=()=>{const d=tenantDishes.find(x=>x.id==b.dataset.id);d.newVersion?versionedDishView(d):dishEditor(d,true)});$$('.dish-edit').forEach(b=>b.onclick=()=>dishEditor(tenantDishes.find(d=>d.id==b.dataset.id)));$$('.dish-toggle').forEach(b=>b.onclick=()=>{const d=tenantDishes.find(x=>x.id==b.dataset.id);d.status=d.status==='已上架'?'已下架':'已上架';showToast(`菜谱已${d.status}`);render('dishes')});$$('.dish-delete').forEach(b=>b.onclick=()=>{const d=tenantDishes.find(x=>x.id==b.dataset.id);showToast(d.authorized?'请先解除全部商户授权后再删除':'菜谱已删除')});$$('.dish-auth-detail').forEach(b=>b.onclick=authorizationDrawer)}
 if(page==='standardDishes'){const filter=()=>{const k=$('#standardKeyword').value.toLowerCase(),s=$('#standardRefState').value;$$('#standardDishBody tr').forEach(r=>r.style.display=(!k||r.dataset.name.toLowerCase().includes(k))&&(!s||r.dataset.state===s)?'':'none')};$('#standardKeyword').oninput=filter;$('#standardRefState').onchange=filter;$$('.standard-view').forEach(b=>b.onclick=()=>standardDetail(standardDishes.find(d=>d.id===b.dataset.id)));$$('.standard-reference').forEach(b=>b.onclick=()=>referenceDrawer([standardDishes.find(d=>d.id===b.dataset.id)]));$('#batchReferenceDish').onclick=()=>{const rows=standardDishes.filter(d=>[...$$('.standard-check:checked')].some(c=>c.value===d.id));rows.length?referenceDrawer(rows):showToast('请先选择需要引用的标准菜谱')}}
 if(page==='dishCategories'){$$('.category-node-v2').forEach(n=>n.onclick=()=>{$$('.category-node-v2').forEach(x=>x.classList.toggle('active',x===n));$('#categoryTitleV2').textContent=n.dataset.category==='all'?'全部分类':n.dataset.category;$$('#categoryBodyV2 tr').forEach(r=>r.style.display=n.dataset.category==='all'||r.dataset.categoryRow===n.dataset.category||r.dataset.parent===n.dataset.category?'':'none')});$('#newPrimaryCategory').onclick=()=>categoryEditor('一级分类');const currentParent=()=>{const v=$('.category-node-v2.active')?.dataset.category||'';if(!v||v==='all')return tenantCategories[0]?.name||'';if(tenantCategories.some(p=>p.name===v))return v;return tenantCategories.find(p=>p.children.includes(v))?.name||tenantCategories[0]?.name||''};$('#newSecondaryCategory').onclick=()=>categoryEditor('二级分类',null,currentParent());$$('.category-edit').forEach(b=>b.onclick=()=>{const tr=b.closest('tr');categoryEditor(tr.dataset.level,{name:tr.dataset.categoryRow,parent:tr.dataset.parent,sort:Number(tr.children[4].textContent)||1},tr.dataset.parent)});$$('.category-toggle').forEach(b=>b.onclick=()=>{const tr=b.closest('tr'),key=categoryMetaKey(tr.dataset.level,tr.dataset.parent,tr.dataset.categoryRow),m=categoryMeta[key],on=m.status==='启用';if(!confirm(on?`确认停用分类“${tr.dataset.categoryRow}”？\n\n停用后已上架菜谱不会自动下架；该分类在菜谱编辑中不可再选择，历史归属保留并显示“已停用”。`:`确认重新启用分类“${tr.dataset.categoryRow}”？`))return;m.status=on?'已停用':'启用';showToast(on?'分类已停用':'分类已启用');render('dishCategories')});$$('.category-delete').forEach(b=>b.onclick=()=>{const tr=b.closest('tr'),level=tr.dataset.level,name=tr.dataset.categoryRow,key=categoryMetaKey(level,tr.dataset.parent,name);const p=tenantCategories.find(x=>x.name===name);if(level==='一级分类'&&p&&p.children.length)return showToast('该一级分类下仍有二级分类，请先处理二级分类');const used=dishCountOf(level==='一级分类'?name:`${tr.dataset.parent} / ${name}`);if(!confirm(`确认删除分类“${name}”？${used?`\n\n当前有 ${used} 个菜谱使用该分类，删除后不会被下架或删除，历史归属保留并显示“已删除”。`:''}`))return;categoryMeta[key].status='已删除';showToast('分类已删除，历史归属已保留');render('dishCategories')})}
 if(page==='dishAuthorization'){$$('[data-auth-view]').forEach(b=>b.onclick=()=>{$$('[data-auth-view]').forEach(x=>x.classList.toggle('active',x===b));$('#authorizationTable').innerHTML=b.dataset.authView==='dish'?authorizationByDish():authorizationByMerchant();bindAuthActions()});$('#newDishAuthorization').onclick=authorizationDrawer;bindAuthActions()}}
function bindAuthActions(){$$('.auth-edit').forEach(b=>b.onclick=authorizationDrawer);$$('.auth-remove').forEach(b=>b.onclick=()=>showToast('已解除所选授权；商户已引用的私域副本不受影响'))}
